<a href="https://colab.research.google.com/github/adityavighne/Python-Basics/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy

In [1]:
! pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [4]:
myarr = np.array([3,6,18,32], np.int64) #allocate memory int8, int32, int64
myarr

array([ 3,  6, 18, 32])

In [7]:
myarr.shape


(4,)

In [8]:
myarr.dtype

dtype('int64')

In [10]:
myarr[0]

3

There are 6 general mechanisms for creating arrays:

    Conversion from other Python structures (i.e. lists and tuples)

    Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

    Replicating, joining, or mutating existing arrays

    Reading arrays from disk, either from standard or custom formats

    Creating arrays from raw bytes through the use of strings or buffers

    Use of special library functions (e.g., random)


**Just creating list array will be created like above**

In [15]:
zeroes = np.zeros((2,5)) # creating zero array
zeroes


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeroes.dtype


dtype('float64')

In [18]:
zeroes.shape

(2, 5)

In [19]:
rng=np.arange(15) #creating array by arange function
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace=np.linspace(1,5,50) #space distance array 
lspace

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [21]:
a=np.empty((4,5)) #random numbers empty array
a

array([[1.2692918e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
        0.0000000e+000]])

In [22]:
b=np.empty_like((1,2))
b

array([25475488, 61440424])

In [23]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
arr.reshape(3,33)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

**Axis in NumPy Array**

row is axis 0<br>
column is axis 1

In [27]:
x = ([1,2,3], [4,5,6],[7,1,0])

In [28]:
ar = np.array(x)
ar
#to transpose array arr.T 
# to get item arr.item
#know dimentions arr.ndim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [29]:
ar.sum(axis = 0)

array([12,  8,  9])

In [30]:
ar.sum(axis =1)

array([ 6, 15,  8])